task: "mcts"

qd:
  n: 10
  p: 0.1
  sigma: 0.01
  generation: 10 # how many generations do we run?
  proportion: 0.2 # top we keep?
  dimensions: 2000
  population: 100
  rep: "turtle"
  game: "smb"

mcts:
  game: "connect_four"
  #maxim: "human"
  #maxim: "alpha_beta_first"
  #maxim: "alpha_beta"
  #minim: "minimax"
  #minim: "alpha_beta"
  #minim: "monte_carlo"
  maxim: "monte_carlo"
  minim: "alpha_beta_first"
  #minim: "random"
  compute: 100
  time: 5
  persistent_tree: True

ann:
  hidden: 30
  epochs: 1000
  silas: 0.00001
  lr: 0.001
