task: "qd"

qd:
  n: 100
  p: 0.1
  sigma: 0.05
  generation: 1000 # how many generations do we run?
  proportion: 0.15 # top we keep?
  dimensions: 2000
  population: 100
  rep: "turtle"
  game: "zelda"

mcts:
  game: "tic_tac_toe"
  maxim: "human"
  minim: "random"
  compute: 10
  c: 0.9
  blahbalh: "sss"

ann:
  hidden: 30
  epochs: 1000
  silas: 0.00001
  lr: 0.001
